import { Restaurant, Branch, User, RestaurantTable, MenuCategory, MenuItem, Order, KitchenOrder, Invoice, Payment } from '../types';

export const INITIAL_RESTAURANT: Restaurant = {
  id: 'rest-green-table',
  name: 'The Green Table',
  slug: 'the-green-table',
  logo_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=240&auto=format&fit=crop&q=80',
  description: 'Contemporary Progressive Indian Dining & Tandoor Craft',
  phone: '+91 98450 12345',
  address: '12th Main Rd, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038',
  gst_number: '29ABCDE1234F1Z5',
  restaurant_type: 'Modern Indian Casual Dining',
  upi_vpa: 'thegreentable@okaxis',
  tax_percentage: 5.0,
  primary_color: '#15803d',
  created_at: new Date('2025-01-01').toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_BRANCH: Branch = {
  id: 'branch-indiranagar',
  restaurant_id: 'rest-green-table',
  name: 'Indiranagar Flagship',
  address: '12th Main Rd, Indiranagar, Bengaluru',
  opening_time: '11:30 AM',
  closing_time: '11:00 PM',
  created_at: new Date('2025-01-01').toISOString(),
};

export const INITIAL_USERS: User[] = [
  {
    id: 'user-1',
    restaurant_id: 'rest-green-table',
    branch_id: 'branch-indiranagar',
    name: 'Aarav Sharma',
    email: 'aarav@thegreentable.com',
    role: 'OWNER',
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'user-2',
    restaurant_id: 'rest-green-table',
    branch_id: 'branch-indiranagar',
    name: 'Priya Nair',
    email: 'priya@thegreentable.com',
    role: 'MANAGER',
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'user-3',
    restaurant_id: 'rest-green-table',
    branch_id: 'branch-indiranagar',
    name: 'Rohan Gupta',
    email: 'rohan@thegreentable.com',
    role: 'CASHIER',
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'user-4',
    restaurant_id: 'rest-green-table',
    branch_id: 'branch-indiranagar',
    name: 'Chef Harish Rawat',
    email: 'chef@thegreentable.com',
    role: 'KITCHEN',
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'user-5',
    restaurant_id: 'rest-green-table',
    branch_id: 'branch-indiranagar',
    name: 'Karan Mehra',
    email: 'karan@thegreentable.com',
    role: 'WAITER',
    created_at: new Date('2025-01-01').toISOString(),
  },
];

export const INITIAL_TABLES: RestaurantTable[] = [
  { id: 'table-1', branch_id: 'branch-indiranagar', table_number: 'T-01', capacity: 2, status: 'AVAILABLE', position_x: 40, position_y: 50, current_order_id: null, created_at: new Date().toISOString() },
  { id: 'table-2', branch_id: 'branch-indiranagar', table_number: 'T-02', capacity: 2, status: 'OCCUPIED', position_x: 200, position_y: 50, current_order_id: 'ord-hist-1', created_at: new Date().toISOString() },
  { id: 'table-3', branch_id: 'branch-indiranagar', table_number: 'T-03', capacity: 4, status: 'ORDERING', position_x: 360, position_y: 50, current_order_id: null, created_at: new Date().toISOString() },
  { id: 'table-4', branch_id: 'branch-indiranagar', table_number: 'T-04', capacity: 4, status: 'AVAILABLE', position_x: 520, position_y: 50, current_order_id: null, created_at: new Date().toISOString() },
  { id: 'table-5', branch_id: 'branch-indiranagar', table_number: 'T-05', capacity: 4, status: 'AVAILABLE', position_x: 40, position_y: 220, current_order_id: null, created_at: new Date().toISOString() }, // Primary Demo Table
  { id: 'table-6', branch_id: 'branch-indiranagar', table_number: 'T-06', capacity: 6, status: 'OCCUPIED', position_x: 200, position_y: 220, current_order_id: 'ord-hist-2', created_at: new Date().toISOString() },
  { id: 'table-7', branch_id: 'branch-indiranagar', table_number: 'T-07', capacity: 6, status: 'PAYMENT_PENDING', position_x: 360, position_y: 220, current_order_id: 'ord-hist-3', created_at: new Date().toISOString() },
  { id: 'table-8', branch_id: 'branch-indiranagar', table_number: 'T-08', capacity: 4, status: 'AVAILABLE', position_x: 520, position_y: 220, current_order_id: null, created_at: new Date().toISOString() },
  { id: 'table-9', branch_id: 'branch-indiranagar', table_number: 'T-09', capacity: 8, status: 'RESERVED', position_x: 120, position_y: 390, current_order_id: null, created_at: new Date().toISOString() },
  { id: 'table-10', branch_id: 'branch-indiranagar', table_number: 'T-10', capacity: 8, status: 'AVAILABLE', position_x: 440, position_y: 390, current_order_id: null, created_at: new Date().toISOString() },
];

export const INITIAL_CATEGORIES: MenuCategory[] = [
  { id: 'cat-starters', restaurant_id: 'rest-green-table', name: 'Small Plates & Starters', sort_order: 1 },
  { id: 'cat-tandoor', restaurant_id: 'rest-green-table', name: 'Tandoor & Grills', sort_order: 2 },
  { id: 'cat-mains', restaurant_id: 'rest-green-table', name: 'Curries & Main Course', sort_order: 3 },
  { id: 'cat-breads', restaurant_id: 'rest-green-table', name: 'Breads, Rice & Biryani', sort_order: 4 },
  { id: 'cat-desserts', restaurant_id: 'rest-green-table', name: 'Artisanal Desserts', sort_order: 5 },
  { id: 'cat-beverages', restaurant_id: 'rest-green-table', name: 'Signature Beverages', sort_order: 6 },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Starters
  {
    id: 'item-1',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-starters',
    name: 'Dahi Ke Kebab',
    description: 'Crispy hung curd croquettes infused with cardamom, green chilies, and fresh mint chutney.',
    image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&auto=format&fit=crop&q=80',
    price: 280,
    vegetarian: true,
    available: true,
    preparation_time: 12,
    addons: [{ id: 'add-mint', name: 'Extra Mint Chutney', price: 30 }],
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-2',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-starters',
    name: 'Kurkuri Bhindi Chaat',
    description: 'Spiced crispy okra slivers tossed with raw mango powder, pomegranate pearls, and tamarind glaze.',
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=400&auto=format&fit=crop&q=80',
    price: 240,
    vegetarian: true,
    available: true,
    preparation_time: 10,
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-3',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-starters',
    name: 'Amritsari Fish Tikka',
    description: 'River sole chunks marinated in ajwain, pounded yellow mustard, and charcoal flame roasted.',
    image_url: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=400&auto=format&fit=crop&q=80',
    price: 420,
    vegetarian: false,
    available: true,
    preparation_time: 16,
    created_at: new Date('2025-01-01').toISOString(),
  },
  // Tandoor
  {
    id: 'item-4',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-tandoor',
    name: 'Tandoori Paneer Tikka',
    description: 'Malai cottage cheese cubes steeped in degi mirch, Greek yogurt, and bell pepper skewers.',
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&auto=format&fit=crop&q=80',
    price: 360,
    vegetarian: true,
    available: true,
    preparation_time: 15,
    variants: [
      { id: 'var-pt-reg', name: 'Classic Portion (4 pcs)', price: 360 },
      { id: 'var-pt-platter', name: 'Sharing Platter (8 pcs)', price: 620 },
    ],
    addons: [
      { id: 'add-cheese', name: 'Extra Melted Cheese', price: 60 },
      { id: 'add-rumali', name: 'Pair with Rumali Roti (1 pc)', price: 45 },
    ],
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-5',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-tandoor',
    name: 'Bhatti Da Murgh',
    description: 'Smoky chicken thighs marinated overnight with roasted spices, garlic, and cooked over direct coals.',
    image_url: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=400&auto=format&fit=crop&q=80',
    price: 460,
    vegetarian: false,
    available: true,
    preparation_time: 18,
    variants: [
      { id: 'var-murgh-half', name: 'Half (4 pcs)', price: 460 },
      { id: 'var-murgh-full', name: 'Full (8 pcs)', price: 790 },
    ],
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-6',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-tandoor',
    name: 'Truffle Mushroom Galouti',
    description: 'Velvety smoked mushroom kebabs seasoned with Kashmiri saffron, served on mini saffron warqi parathas.',
    image_url: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=400&auto=format&fit=crop&q=80',
    price: 380,
    vegetarian: true,
    available: true,
    preparation_time: 15,
    created_at: new Date('2025-01-01').toISOString(),
  },
  // Mains
  {
    id: 'item-7',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-mains',
    name: 'Dal Makhani 24-Hour',
    description: 'Black lentils slow cooked overnight on charcoal embers with white butter and vine-ripened tomatoes.',
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&auto=format&fit=crop&q=80',
    price: 340,
    vegetarian: true,
    available: true,
    preparation_time: 12,
    addons: [{ id: 'add-butter', name: 'Dollop of Cultured Makhan', price: 40 }],
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-8',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-mains',
    name: 'Old Delhi Butter Chicken',
    description: 'Charred tandoori chicken simmered in rich creamy velvet tomato gravy with dried fenugreek honey touch.',
    image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400&auto=format&fit=crop&q=80',
    price: 490,
    vegetarian: false,
    available: true,
    preparation_time: 16,
    variants: [
      { id: 'var-bc-regular', name: 'Regular Portion', price: 490 },
      { id: 'var-bc-large', name: 'Boneless Special', price: 540 },
    ],
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-9',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-mains',
    name: 'Paneer Lababdar',
    description: 'Soft cottage cheese simmered in chunky onion-tomato masala with crushed coriander and cream.',
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&auto=format&fit=crop&q=80',
    price: 390,
    vegetarian: true,
    available: true,
    preparation_time: 14,
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-10',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-mains',
    name: 'Rawalpindi Chole',
    description: 'Rustic spiced chickpeas braised with anardana, amla, and carom seeds, served steaming hot.',
    image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&auto=format&fit=crop&q=80',
    price: 310,
    vegetarian: true,
    available: true,
    preparation_time: 12,
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-11',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-mains',
    name: 'Laal Maas',
    description: 'Fiery Rajasthani spring lamb curry infused with Mathania red chilies and smoked mustard oil.',
    image_url: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=400&auto=format&fit=crop&q=80',
    price: 580,
    vegetarian: false,
    available: true,
    preparation_time: 20,
    created_at: new Date('2025-01-01').toISOString(),
  },
  // Breads & Rice
  {
    id: 'item-12',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-breads',
    name: 'Butter Garlic Naan',
    description: 'Leavened refined flour flatbread studded with minced roasted garlic and brushed with fresh butter.',
    image_url: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=400&auto=format&fit=crop&q=80',
    price: 90,
    vegetarian: true,
    available: true,
    preparation_time: 6,
    addons: [{ id: 'add-cheese-naan', name: 'Cheese Stuffed Upgrade', price: 60 }],
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-13',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-breads',
    name: 'Laccha Paratha',
    description: 'Flaky multi-layered whole wheat bread baked golden in the tandoor with ghee.',
    image_url: 'https://images.unsplash.com/photo-1505253758473-96b46deae039?w=400&auto=format&fit=crop&q=80',
    price: 75,
    vegetarian: true,
    available: true,
    preparation_time: 6,
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-14',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-breads',
    name: 'Dum Awadhi Gosht Biryani',
    description: 'Aged basmati rice sealed with tender mutton cuts, rose water, kewra, and brown onions on dum.',
    image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&auto=format&fit=crop&q=80',
    price: 520,
    vegetarian: false,
    available: true,
    preparation_time: 20,
    addons: [{ id: 'add-raita', name: 'Burani Garlic Raita', price: 50 }],
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-15',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-breads',
    name: 'Subz Nizami Biryani',
    description: 'Garden vegetables and cottage cheese dum pukht style with fragrant herbs and saffron strands.',
    image_url: 'https://images.unsplash.com/photo-1642821373181-696a54913e9a?w=400&auto=format&fit=crop&q=80',
    price: 380,
    vegetarian: true,
    available: true,
    preparation_time: 15,
    created_at: new Date('2025-01-01').toISOString(),
  },
  // Desserts
  {
    id: 'item-16',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-desserts',
    name: 'Gulab Jamun with Rabri',
    description: 'Warm khoya dumplings filled with pistachio center, bathed in cardamom syrup and chilled malai rabri.',
    image_url: 'https://images.unsplash.com/photo-1589119908995-c6837fa14d48?w=400&auto=format&fit=crop&q=80',
    price: 210,
    vegetarian: true,
    available: true,
    preparation_time: 8,
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-17',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-desserts',
    name: 'Kesar Pista Kulfi Falooda',
    description: 'Traditional slow-reduced saffron clotted ice cream topped with rose vermicelli and basil seeds.',
    image_url: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=400&auto=format&fit=crop&q=80',
    price: 240,
    vegetarian: true,
    available: true,
    preparation_time: 6,
    created_at: new Date('2025-01-01').toISOString(),
  },
  // Beverages
  {
    id: 'item-18',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-beverages',
    name: 'Masala Chaas',
    description: 'Churned spiced buttermilk seasoned with roasted cumin seeds, Himalayan black salt, and ginger.',
    image_url: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=400&auto=format&fit=crop&q=80',
    price: 110,
    vegetarian: true,
    available: true,
    preparation_time: 4,
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-19',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-beverages',
    name: 'Alphonso Mango Lassi',
    description: 'Thick creamy yogurt blended with Ratnagiri alphonso mango pulp and garnished with chopped pistachios.',
    image_url: 'https://images.unsplash.com/photo-1570696516188-ade861b84a49?w=400&auto=format&fit=crop&q=80',
    price: 160,
    vegetarian: true,
    available: true,
    preparation_time: 5,
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-20',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-beverages',
    name: 'Kokum Shikanji Soda',
    description: 'Refreshing coastal kokum infusion spiked with chaat spices, freshly squeezed lemon, and bubbly soda.',
    image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400&auto=format&fit=crop&q=80',
    price: 140,
    vegetarian: true,
    available: true,
    preparation_time: 4,
    created_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'item-21',
    restaurant_id: 'rest-green-table',
    category_id: 'cat-beverages',
    name: 'Craft Thums Up Float',
    description: 'Classic Indian cola served in a chilled beer mug with artisanal Madagascar vanilla bean gelato scoop.',
    image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400&auto=format&fit=crop&q=80',
    price: 130,
    vegetarian: true,
    available: true,
    preparation_time: 3,
    created_at: new Date('2025-01-01').toISOString(),
  },
];

export const INITIAL_HISTORICAL_ORDERS: Order[] = [
  {
    id: 'ord-hist-1',
    restaurant_id: 'rest-green-table',
    branch_id: 'branch-indiranagar',
    table_id: 'table-2',
    table_number: 'T-02',
    order_number: 'ORD-1038',
    source: 'QR',
    status: 'PREPARING',
    subtotal: 800,
    discount: 0,
    tax: 40,
    total: 840,
    payment_status: 'PENDING',
    customer_name: 'Vikram Patel',
    customer_phone: '+91 98111 22334',
    items: [
      {
        id: 'oi-1',
        order_id: 'ord-hist-1',
        menu_item_id: 'item-4',
        menu_item_name: 'Tandoori Paneer Tikka',
        quantity: 1,
        unit_price: 360,
        total_price: 360,
        notes: 'Extra spicy mint dip',
      },
      {
        id: 'oi-2',
        order_id: 'ord-hist-1',
        menu_item_id: 'item-7',
        menu_item_name: 'Dal Makhani 24-Hour',
        quantity: 1,
        unit_price: 340,
        total_price: 340,
      },
      {
        id: 'oi-3',
        order_id: 'ord-hist-1',
        menu_item_id: 'item-20',
        menu_item_name: 'Kokum Shikanji Soda',
        quantity: 1,
        unit_price: 140,
        total_price: 140,
      },
    ],
    created_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord-hist-2',
    restaurant_id: 'rest-green-table',
    branch_id: 'branch-indiranagar',
    table_id: 'table-6',
    table_number: 'T-06',
    order_number: 'ORD-1039',
    source: 'POS',
    status: 'SERVED',
    subtotal: 1680,
    discount: 100,
    tax: 79,
    total: 1659,
    payment_status: 'PENDING',
    items: [
      {
        id: 'oi-4',
        order_id: 'ord-hist-2',
        menu_item_id: 'item-5',
        menu_item_name: 'Bhatti Da Murgh',
        quantity: 1,
        unit_price: 460,
        total_price: 460,
      },
      {
        id: 'oi-5',
        order_id: 'ord-hist-2',
        menu_item_id: 'item-8',
        menu_item_name: 'Old Delhi Butter Chicken',
        quantity: 1,
        unit_price: 490,
        total_price: 490,
      },
      {
        id: 'oi-6',
        order_id: 'ord-hist-2',
        menu_item_id: 'item-12',
        menu_item_name: 'Butter Garlic Naan',
        quantity: 3,
        unit_price: 90,
        total_price: 270,
      },
      {
        id: 'oi-7',
        order_id: 'ord-hist-2',
        menu_item_id: 'item-19',
        menu_item_name: 'Alphonso Mango Lassi',
        quantity: 2,
        unit_price: 160,
        total_price: 320,
      },
      {
        id: 'oi-8',
        order_id: 'ord-hist-2',
        menu_item_id: 'item-14',
        menu_item_name: 'Dum Awadhi Gosht Biryani',
        quantity: 1,
        unit_price: 520,
        total_price: 520,
      },
    ],
    created_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord-hist-3',
    restaurant_id: 'rest-green-table',
    branch_id: 'branch-indiranagar',
    table_id: 'table-7',
    table_number: 'T-07',
    order_number: 'ORD-1040',
    source: 'WAITER',
    status: 'BILLED',
    subtotal: 1240,
    discount: 0,
    tax: 62,
    total: 1302,
    payment_status: 'PENDING',
    items: [
      {
        id: 'oi-9',
        order_id: 'ord-hist-3',
        menu_item_id: 'item-9',
        menu_item_name: 'Paneer Lababdar',
        quantity: 1,
        unit_price: 390,
        total_price: 390,
      },
      {
        id: 'oi-10',
        order_id: 'ord-hist-3',
        menu_item_id: 'item-15',
        menu_item_name: 'Subz Nizami Biryani',
        quantity: 1,
        unit_price: 380,
        total_price: 380,
      },
      {
        id: 'oi-11',
        order_id: 'ord-hist-3',
        menu_item_id: 'item-12',
        menu_item_name: 'Butter Garlic Naan',
        quantity: 2,
        unit_price: 90,
        total_price: 180,
      },
      {
        id: 'oi-12',
        order_id: 'ord-hist-3',
        menu_item_id: 'item-16',
        menu_item_name: 'Gulab Jamun with Rabri',
        quantity: 1,
        unit_price: 210,
        total_price: 210,
      },
      {
        id: 'oi-13',
        order_id: 'ord-hist-3',
        menu_item_id: 'item-18',
        menu_item_name: 'Masala Chaas',
        quantity: 1,
        unit_price: 110,
        total_price: 110,
      },
    ],
    created_at: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  // Paid orders earlier today for meaningful analytics
  {
    id: 'ord-hist-past-1',
    restaurant_id: 'rest-green-table',
    branch_id: 'branch-indiranagar',
    table_id: 'table-1',
    table_number: 'T-01',
    order_number: 'ORD-1035',
    source: 'POS',
    status: 'PAID',
    subtotal: 920,
    discount: 50,
    tax: 43.5,
    total: 913.5,
    payment_status: 'SUCCESS',
    items: [
      { id: 'p-1', order_id: 'ord-hist-past-1', menu_item_id: 'item-4', menu_item_name: 'Tandoori Paneer Tikka', quantity: 1, unit_price: 360, total_price: 360 },
      { id: 'p-2', order_id: 'ord-hist-past-1', menu_item_id: 'item-7', menu_item_name: 'Dal Makhani 24-Hour', quantity: 1, unit_price: 340, total_price: 340 },
      { id: 'p-3', order_id: 'ord-hist-past-1', menu_item_id: 'item-18', menu_item_name: 'Masala Chaas', quantity: 2, unit_price: 110, total_price: 220 },
    ],
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3.2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord-hist-past-2',
    restaurant_id: 'rest-green-table',
    branch_id: 'branch-indiranagar',
    table_id: 'table-5',
    table_number: 'T-05',
    order_number: 'ORD-1036',
    source: 'QR',
    status: 'PAID',
    subtotal: 1450,
    discount: 0,
    tax: 72.5,
    total: 1522.5,
    payment_status: 'SUCCESS',
    items: [
      { id: 'p-4', order_id: 'ord-hist-past-2', menu_item_id: 'item-8', menu_item_name: 'Old Delhi Butter Chicken', quantity: 1, unit_price: 490, total_price: 490 },
      { id: 'p-5', order_id: 'ord-hist-past-2', menu_item_id: 'item-14', menu_item_name: 'Dum Awadhi Gosht Biryani', quantity: 1, unit_price: 520, total_price: 520 },
      { id: 'p-6', order_id: 'ord-hist-past-2', menu_item_id: 'item-12', menu_item_name: 'Butter Garlic Naan', quantity: 2, unit_price: 90, total_price: 180 },
      { id: 'p-7', order_id: 'ord-hist-past-2', menu_item_id: 'item-19', menu_item_name: 'Alphonso Mango Lassi', quantity: 1, unit_price: 160, total_price: 160 },
      { id: 'p-8', order_id: 'ord-hist-past-2', menu_item_id: 'item-21', menu_item_name: 'Craft Thums Up Float', quantity: 1, unit_price: 130, total_price: 130 },
    ],
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord-hist-past-3',
    restaurant_id: 'rest-green-table',
    branch_id: 'branch-indiranagar',
    table_id: 'table-8',
    table_number: 'T-08',
    order_number: 'ORD-1037',
    source: 'POS',
    status: 'PAID',
    subtotal: 730,
    discount: 0,
    tax: 36.5,
    total: 766.5,
    payment_status: 'SUCCESS',
    items: [
      { id: 'p-9', order_id: 'ord-hist-past-3', menu_item_id: 'item-1', menu_item_name: 'Dahi Ke Kebab', quantity: 1, unit_price: 280, total_price: 280 },
      { id: 'p-10', order_id: 'ord-hist-past-3', menu_item_id: 'item-9', menu_item_name: 'Paneer Lababdar', quantity: 1, unit_price: 390, total_price: 390 },
      { id: 'p-11', order_id: 'ord-hist-past-3', menu_item_id: 'item-20', menu_item_name: 'Kokum Shikanji Soda', quantity: 1, unit_price: 140, total_price: 140 },
    ],
    created_at: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_KITCHEN_ORDERS: KitchenOrder[] = [
  {
    id: 'ko-1',
    order_id: 'ord-hist-1',
    table_id: 'table-2',
    table_number: 'T-02',
    order_number: 'ORD-1038',
    status: 'PREPARING',
    items: [
      { id: 'koi-1', name: 'Tandoori Paneer Tikka', quantity: 1, notes: 'Extra spicy mint dip' },
      { id: 'koi-2', name: 'Dal Makhani 24-Hour', quantity: 1 },
      { id: 'koi-3', name: 'Kokum Shikanji Soda', quantity: 1 },
    ],
    created_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'ko-2',
    order_id: 'ord-hist-2',
    table_id: 'table-6',
    table_number: 'T-06',
    order_number: 'ORD-1039',
    status: 'READY',
    items: [
      { id: 'koi-4', name: 'Bhatti Da Murgh', quantity: 1 },
      { id: 'koi-5', name: 'Old Delhi Butter Chicken', quantity: 1 },
      { id: 'koi-6', name: 'Butter Garlic Naan', quantity: 3 },
      { id: 'koi-7', name: 'Alphonso Mango Lassi', quantity: 2 },
      { id: 'koi-8', name: 'Dum Awadhi Gosht Biryani', quantity: 1 },
    ],
    created_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    order_id: 'ord-hist-past-1',
    amount: 913.5,
    method: 'UPI_QR',
    status: 'SUCCESS',
    transaction_ref: 'UPI/2026/0920/1035',
    is_demo: false,
    created_at: new Date(Date.now() - 3.2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'pay-2',
    order_id: 'ord-hist-past-2',
    amount: 1522.5,
    method: 'UPI_INTENT',
    status: 'SUCCESS',
    transaction_ref: 'UPI/2026/0920/1036',
    is_demo: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'pay-3',
    order_id: 'ord-hist-past-3',
    amount: 766.5,
    method: 'CASH',
    status: 'SUCCESS',
    transaction_ref: 'CASH-REC-1037',
    is_demo: false,
    created_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
  },
];
